#資料庫
spring.datasource.username=BT3500
spring.datasource.password=BT3500
spring.datasource.jdbc-url=jdbc:oracle:thin:@10.1.1.205:1521:iotbs
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.config.location=C:/foyatech_workspace/Training_2/conf/csvparser.properties
logging.config=C:/foyatech_workspace/Training_2/conf/log4j2.xml