debug=true

#程式根目錄
project-path=C:/foyatech_workspace/Training_2

#資料庫
spring.datasource.username=
spring.datasource.password=
spring.datasource.jdbc-url=jdbc:oracle:thin:@
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.datasource.username=
#spring.datasource.password=
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:localhost
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.oracle.initial-size=1
spring.datasource.oracle.maximum-pool-size=1
spring.datasource.oracle.minimum-idle=1
spring.datasource.oracle.autocommit=false

#batch cron
cron.expression=0 */1 * * * ?

#batch recycle (ms)
fixedDelayString.expression=600000

#batch just run one time
batch.runOnce=true

#log4j2 設定檔
logging.config=${project-path}/conf/log4j2.xml

#input/output/insert_table 格式設定檔
format-config-file=${project-path}/conf/csv2fix.xml

#來源檔路徑
input-file-path=${project-path}/input
#來源檔附檔名
input-file-extension=csv

#處理成功檔 - 產檔路徑
output-file-path=${project-path}/output
#處理成功檔附檔名
output-file-extension=fix

#處理失敗檔 - 產檔路徑
error-file-path=${project-path}/error
#處理失敗檔附檔名
error-file-extension=err

#程式參數
file.type=CSV

#是否自動執行Job，預設true，需要定時任務或手動觸發請置為false
spring.batch.job.enabled=false

#把SPRING的圖案去掉
spring.main.banner-mode=off

#是否生成執行狀態記錄的表結構
spring.batch.initializer.enabled = false

spring.devtools.livereload.enabled=false
